### ISSUE TITLE
It is not working here... 

### ISSUE THREAD

**Issue by falbinosantos** [k4m4/kickthemout#231]
I just realized that, in truth the script is not working here. I'm making some tests trying to kick off some of my devices (iPhone 6s Plus, iPad Pro 9.7) and the connection still working as usual.

Then I tried to kick a laptop using the script and I tracked the laptop connection by the router IP address and the laptop still receiving and sending data.

**Comment by k4m4** [comment]
Hi there. KickThemOut uses ARP-Spoofing in order to 'kick' devices off ones Local Area Network. An ARP-Spoof attack [will not always be 100% efficient](https://security.stackexchange.com/questions/52289/why-the-arp-entry-of-the-router-recover-so-quickly-after-arp-poisoning). Our script's main purpose is to save bandwidth for the attacker. This means that the less packets sent out to the victim, the less traffic, and therefore the more bandwidth. In order to maximize efficiency for what **you** are trying to accomplish, you can increase the number of packets sent out to victims. However, this means that more traffic will be created on you network. @xdavidhu and I are currently working on a new release that will allow for more attack vectors. Thank you for your feedback.
