### ISSUE TITLE
How long does the spoofing process take?

### ISSUE THREAD

**Issue by stanix96** [k4m4/kickthemout#256]
Hey, just a quick question. Everything is working fine, but i'm asking me, how long does the spoofing process take?

I selected my mobile phone to be kicked out but nothing happens. It runs now about 25 minutes.

**Comment by chowdaryidavalapati** [comment]
**Spoofing started...**

- I have also the similar problem with `Spoofing started...`.
- I run this `sudo python3 kickthemout.py --target 192.168.1.16` command on my ubuntu machine. But it was stuck at `Spoofing started...`

**Comment by 45ashok** [comment]
i also have the same problem

**Comment by 45ashok** [comment]
i got stuck at spoofing started.i cant kick out any device

**Comment by k4m4** [comment]
Hi there. KickThemOut uses ARP-Spoofing in order to 'kick' devices off one's Local Area Network. An ARP-Spoof attack will not always be 100% efficient. Our script's main purpose is to save bandwidth for the attacker. This means that the less packets sent out to the victim, the less traffic, and therefore the more bandwidth. In order to maximize efficiency for what you are trying to accomplish, you can increase the number of packets sent out to victims. However, this would mean that more traffic will be created on you network. If you still have any questions, please re-open this issue. Thanks!

**Comment by guinevereperez** [comment]
> Hi there. KickThemOut uses ARP-Spoofing in order to 'kick' devices off one's Local Area Network. An ARP-Spoof attack will not always be 100% efficient. Our script's main purpose is to save bandwidth for the attacker. This means that the less packets sent out to the victim, the less traffic, and therefore the more bandwidth. In order to maximize efficiency for what you are trying to accomplish, you can increase the number of packets sent out to victims. However, this would mean that more traffic will be created on you network. If you still have any questions, please re-open this issue. Thanks!

I still have a question: If I leave it running on the "spoofing started" will it at least help keep people off my network?

**Comment by k4m4** [comment]
Hi there @guinevereperez. KickThemOut will continue sending ARP spoof packets until you hit `^C`.

**Comment by LahaLuhem** [comment]
> Hi there. KickThemOut uses ARP-Spoofing in order to 'kick' devices off one's Local Area Network. An ARP-Spoof attack will not always be 100% efficient. Our script's main purpose is to save bandwidth for the attacker. This means that the less packets sent out to the victim, the less traffic, and therefore the more bandwidth. In order to maximize efficiency for what you are trying to accomplish, you can increase the number of packets sent out to victims. However, this would mean that more traffic will be created on you network. If you still have any questions, please re-open this issue. Thanks!

How can I increase the number of spoof packets sent to the victims?
