### ISSUE TITLE
HEEELP 

### ISSUE THREAD

**Issue by franco2222** [k4m4/kickthemout#263]
MACBOOK AIR OSX YOSEMITE - en0
kickthemout is very slow and it doesn't work, 

I dont un
kickthemout> 3

kickALLOff selected...

Target(s): 
  [0] xxxxxxxxxxxx	xxxxxxxxxxxxxxxxApple, Inc. (N/A)
  [1] xxxxxxxxxxxx	xxxxxxxxxxxxxxxx	Sony Mobile Communication (N/A)
  [2] xxxxxxxxxxxx	xxxxxxxxxxxxxxxx	Sony Mobile Communication (N/A)
  [3] xxxxxxxxxxxx	xxxxxxxxxxxxxxxx	Apple, Inc. (N/A)
  [4] xxxxxxxxxxxx	xxxxxxxxxxxxxxxx LG Electronics (Mobile Co (N/A)
Spoofing started...

**Comment by Devloger** [comment]
I have
Spoofing started...
And nothing more + it doesn't work.

**Comment by 45ashok** [comment]
i cant kick out any device

**Comment by andreasgtech** [comment]
I can't kick devices too, I have mentioned this not-working issue before, but it got rejected after not getting any response for a long time...

**Comment by k4m4** [comment]
Hi there. KickThemOut uses ARP-Spoofing in order to 'kick' devices off one's Local Area Network. An ARP-Spoof attack will not always be 100% efficient. Our script's main purpose is to save bandwidth for the attacker. This means that the less packets sent out to the victim, the less traffic, and therefore the more bandwidth. In order to maximize efficiency for what you are trying to accomplish, you can increase the number of packets sent out to victims. However, this would mean that more traffic will be created on you network. If you still have any questions, please re-open this issue. Thanks!
