### ISSUE TITLE
Re-arping target OSX Error

### ISSUE THREAD

**Issue by RSickenberg** [k4m4/kickthemout#27]
```
Re-arping targets...
Traceback (most recent call last):
  File "kickthemout.py", line 319, in <module>
    main()
  File "kickthemout.py", line 302, in main
    kickalloff()
  File "kickthemout.py", line 210, in kickalloff
    spoof.sendPacket(defaultGatewayMac, defaultGatewayIP, host[0], host[1])
NameError: global name 'defaultGatewayMac' is not defined
```

**Comment by k4m4** [comment]
Interesting. Let me look into it.

**Comment by psycheskunky** [comment]
Hi, 
I have the same problem.
Any issues? 

Thanks

**Comment by realryanpark** [comment]
Is this still an issue, or has it been resolved?

**Comment by RSickenberg** [comment]
Still an issue

**Comment by k4m4** [comment]
Sorry guys. We're on it.

**Comment by MI5T3R-H4CK3R** [comment]
I'm having the same problem, any news on fixing it?
I am in desperate need to kick my family off the wifi!

**Comment by k4m4** [comment]
Sorry for the delay guys. We have created a debug function to run when this issue occurs. Please try running KickThemOut again and post the results in this issue asap. Thanks! @MI5T3R-H4CK3R @RSickenberg @realryanpark

**Comment by MI5T3R-H4CK3R** [comment]
Sorry I am a bit of a noob.
Should I have reinstalled KickThemOut from github before running it.
If so how to I do that.
Also I've noticed that kickthemout.py takes several minutes to startup and another few minutes when I have selected KickOneoff. Is this normal?

**Comment by xdavidhu** [comment]
@MI5T3R-H4CK3R Delete the whole kickthemout folder, and clone it again. If it crashes again, please post the debug info for us here.

------

We are working on a fix for the long scanning times, but its not implemented yet.

**Comment by psycheskunky** [comment]
Yes u can clone again from git Send from Huawei KIW-L21-------- Message original --------Objet : Re: [k4m4/kickthemout] Re-arping target OSX Error (#27)De : MI5T3R-H4CK3R À : k4m4/kickthemout Cc : psycheskunky ,Comment Sorry I am a bit of a noob.
Should I have reinstalled KickThemOut from github before running it.
If so how to I do that.
Also I've noticed that kickthemout.py takes several minutes to startup and another few minutes when I have selected KickOneoff. Is this normal?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/k4m4/kickthemout","title":"k4m4/kickthemout","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/k4m4/kickthemout"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MI5T3R-H4CK3R in #27: Sorry I am a bit of a noob.\r\nShould I have reinstalled KickThemOut from github before running it.\r\nIf so how to I do that.\r\nAlso I've noticed that kickthemout.py takes several minutes to startup and another few minutes when I have selected KickOneoff. Is this normal?"}],"action":{"name":"View Issue","url":"https://github.com/k4m4/kickthemout/issues/27#issuecomment-279982984"}}}

**Comment by MI5T3R-H4CK3R** [comment]
I did that and now I get a new error:
ERROR: Default Gateway MAC Address could not be obtained. Please enter MAC manually.
Can I fix this or must I enter my MAC address manually?

**Comment by MI5T3R-H4CK3R** [comment]
I've never had this error before

**Comment by xdavidhu** [comment]
Yes, that is part of the new fix.

For some reason, looks like kickthemout cant get it automaticly, so you have to enter it manually to prevent it from crashing. Keep that in mind that the router's MAC address is what you need to enter.

**Comment by MI5T3R-H4CK3R** [comment]
Thanks, every thing worked fine with the bug fix, however I still haven't been able to kick someone.
I've selected a target then it says spoofing started. I then wait about 30secs like in the demo vid then I re-arp the target with ctrl c then it says Re-arped target successfully and returns to the main menu. however my target is still connected to the wifi. Am I doing something wrong?

Sorry for all these questions, I have only just got to grips with using lxterminal. So I am a bit new to all this.

**Comment by xdavidhu** [comment]
@MI5T3R-H4CK3R No worries.

You have to keep kickthemout running to keep them offline.
When you press CTRL+C you basically stopping it, and giving the internet back to the target. So you will have to let it run, and if you want to stop spoofing, just CTRL+C it.

Btw check out the video JackkTutorials made about kickthemout. That is the best tutorial: https://youtu.be/n6G3Nw4qDzg

**Comment by MI5T3R-H4CK3R** [comment]
thanks but it still didn't work I am trying to kick an iPhone and I'm running kickthemout on a raspberry pi 3.

**Comment by MI5T3R-H4CK3R** [comment]
I have done everything you said before. I don't know if this will help but I used arp -a to get my routers make address.

**Comment by RSickenberg** [comment]
`ERROR: Default Gateway MAC Address could not be obtained. Please enter MAC manually.`

**Comment by RSickenberg** [comment]
It's fine now 👍
