### ISSUE TITLE
I cant kick people out of wifi

### ISSUE THREAD

**Issue by Alodn1** [k4m4/kickthemout#310]
whenever I go on kickthemout kali linux it only shows the same ips default gateway/ or number how ever u say it whenever im not in my home it still shows the same ROUTER when i am at school

**Comment by k4m4** [comment]
Hi there @Alodn1. I am unsure if I have understood your question; even so, from what I've understood, this isn't a problem. It's usual to get the same default router IP address (e.g. 192.168.1.1) in several LAN networks. If there's anything else, please do not hesitate to ask. Thanks.

**Comment by Alodn1** [comment]
I mean that when I use Kickthemout at home it shows the IP or router not sure and when i type 3 for all it does not kick them out... so then i tried to go to school and opened kickthemout it will still show the same ROUTER or IP not sure but not the school ones so is it too change or not? plz help i rlly want to kick people out :D

**Comment by Alodn1** [comment]
like the Gateway IP

**Comment by Alodn1** [comment]
Yes, and idk which devices are where from cuz im trying to kick people out of my school wifi but only shows 3 devices

**Comment by k4m4** [comment]
So, the issue is that you can't find the devices that you are targeting or that the ARP-spoofing attack isn't working?

**Comment by Alodn1** [comment]
Both

**Comment by Alodn1** [comment]
Both of them, ARP-spoofing aint working, can't find the device I'm looking for only shows up 3 devices one of them is a gateway and 2 is normal devices

**Comment by k4m4** [comment]
Can you please share with us the information that is asked for in the issue template (i.e. python version, OS etc.)? Thanks again.

**Comment by Ap1paddr4** [comment]
Hi so i installed kickthemout on my home network working perfect kicking out whoever is connected, i was going to try it at work,  i can find devices and their IP but doesn't kick any of them out ( i tried my work pc ). Does it need to be installed or reinstalled on each network? Or do i have to change smth? thank you

**Comment by Alodn1** [comment]
I am using mac os x and when i try to kick out someone it doesnt work at all

**Comment by k4m4** [comment]
Hey guys. So, KickThemOut uses ARP-Spoofing in order to 'kick' devices off one's Local Area Network. An ARP-Spoof attack [will not always be 100% efficient](https://security.stackexchange.com/questions/52289/why-the-arp-entry-of-the-router-recover-so-quickly-after-arp-poisoning). Our script's main purpose is to save bandwidth for the attacker. This means that the less packets sent out to the victim, the less traffic created, and therefore the more bandwidth. In order to maximize efficiency for what **you** are trying to accomplish, you can increase the number of packets sent out to victims using the `-p` flag. However, this means that more traffic will be created on you network. If you have any further questions, please don't hesitate to reopen this issue. Thanks!

**Comment by Halpmewithdis** [comment]
i have the same issue please help
