### ISSUE TITLE
Iphone device have still internet 

### ISSUE THREAD

**Issue by HannHank** [k4m4/kickthemout#343]
It is working very well with Android, but if i try to block an Iphone from my Wifi it still has Internet

**Comment by k4m4** [comment]
Hi there. From what I have noticed, this is probably because iOS sends reconnection packets to the router every _x_ time interval, regaining connection using the correct MAC address. However, I am not too sure about that and will look into it. In the meantime, try using the `-p` flag to increase the number of ARP spoof packets sent.
