### ISSUE TITLE
No module named 'scapy.config' On Mac OS

### ISSUE THREAD

**Issue by selbyh1** [k4m4/kickthemout#352]
## Checklist for submitting an issue to `KickThemOut`:

- [ ] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [ ] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [ ] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: 
- **Scapy version**: 
- **Nmap version**: 

Sarah:kickthemout selbyhardwick$ sudo -H pip3 install -r requirements.txt
Requirement already satisfied: scapy-python3 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (0.26)
Requirement already satisfied: python-nmap in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (0.6.1)
Requirement already satisfied: netifaces in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (0.10.7)
Sarah:kickthemout selbyhardwick$ sudo python3 kickthemout.py

and I still get!!!

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: No module named 'scapy.config'

**Comment by selbyh1** [comment]
Os= Mac 2014 OS X
Python= 3
Scapy=0.26
Nmap=6.1

**Comment by SevenChords** [comment]
same problem here

**Comment by SevenChords** [comment]
ok, i think i figured out what the issue is, now someone just needs to resolve that, the kickthemout uses a now deprecated python3 port of scapy, which is where there would be a config module, the mainstream scapy on the other hand, which is always installed since the python3 port is deprecated, has no scapy.config module, according to the error messages i got through trial and error that module has been moved to a package called kamene.
if that is really the issue you would have to re-code kickthemout to use kamene and mainstream scapy (which is python3 compatible since version 2.x) instead of scapy-python3.

**Comment by Mahmoud-Eltobgy** [comment]
same problem on ubuntu 18

**Comment by k4m4** [comment]
Hey guys. Please try to reinstall KickThemOut and all its dependencies; I have upgraded `Scapy` to the latest `Kamene` build which should resolve this dependency error. Please re-open the issue if the problem persists. Thanks!
