### ISSUE TITLE
How to install tcpdump

### ISSUE THREAD

**Issue by cahyosh** [k4m4/kickthemout#394]
Can anyone here tell me how to install tcpdump.
My kickthemout missing tcpdump
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH

**Comment by k4m4** [comment]
Hi there. It depends on what OS you are using. If you are using Linux, then `apt install tcpdump` should do the job. Otherwise, just Google "how to install `tcpdump` on {OS}". Let me know if there's any KickThemOut-specific issues I can help you with. Closing since this is unrelated to KickThemOut. Thanks.
