### ISSUE TITLE
can't install requirements.txt

### ISSUE THREAD

**Issue by zaldhyx77** [k4m4/kickthemout#7]
`[zaldhy77@asus kickthemout-0.1]$ sudo pip install -r requirements.txt`
```
Collecting scapy (from -r requirements.txt (line 1))
  Downloading scapy-2.3.3.tgz (1.4MB)
    100% |████████████████████████████████| 1.4MB 125kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xz4btw2v/scapy/setup.py", line 36
        os.chmod(fname, 0755)
                           ^
    SyntaxError: invalid token
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xz4btw2v/scapy/

```

**Comment by k4m4** [comment]
This is an error which most probably occurs due to python on your machine.

Try running the following:

`$ pip3 install scapy-python3`

If this doesn't solve the error, try downloading scapy using a different installation method (try [here](http://www.secdev.org/projects/scapy/doc/installation.html)).
Let me know if there is still an issue then. 

Generally, scapy is a bit of a pain in the back when it comes to mac & windows.

**Comment by xdavidhu** [comment]
Try running this to reinstall pip before installing the dependencies:
```
sudo apt-get purge python-pip && sudo apt-get install python-pip
```

and also with pip3:
```
sudo apt-get purge python3-pip && sudo apt-get install python3-pip
```
