### ISSUE TITLE
Question - Can this script be executed on an iOS jailbroken device?

### ISSUE THREAD

**Issue by LeoZango** [k4m4/kickthemout#77]
I am aware of how to run python scripts through mTerminal though I know there are additional requirements which have to be satisfied (by installing plugins) to run the script.

Is there any way to do to this on an iOS device?

Thanks

**Comment by k4m4** [comment]
Hi there buddy. So, KickThemOut is based on a Python framework called `scapy`. Generally speaking, it isn't one of my favorite libs; however, there aren't many other, better options. Unfortunately, it is most likely that you cannot run KickThemOut on a jailbroken iOS device due to scapy's lack of compatibility with the device.

**Comment by LeoZango** [comment]
Ok, thanks for letting me know. I thought the scapy plugin may be incompatible.

**Comment by k4m4** [comment]
No problem. :)
