### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by horus1** [k4m4/kickthemout#90]
ERROR: Default Gateway MAC Address could not be obtained. Please enter MAC manually.

**Comment by hkessel1** [comment]
Same here...

**Comment by k4m4** [comment]
Hi there. In a recent commit, we changed the whole scanning process in order to improve usability and resolve issues previously raised. Please try following the new installation procedure. (Also make sure to `$ git pull`).
If this error still occurs, please let us know and we'll re-open the issue.
Thank you all.
