### ISSUE TITLE
python kickthemout.py won't run

### ISSUE THREAD

**Issue by SimplyPeace** [k4m4/kickthemout#92]
The program won't seem to launch at all, it just lingers on a blank space. Is there way around this? I should have all of the requirements installed.

**Comment by k4m4** [comment]
Hi there. In a recent commit, we changed the whole scanning process in order to improve usability and resolve issues previously raised. Please try following the new installation procedure located in the README file. (Also make sure to `$ git pull`).
If this error still occurs, please let us know and we'll re-open the issue.
Thank you.

**Comment by td0** [comment]
me too. Just installed kickthemout last night, all dependencies have been installed. When I try to run "sudo python kickthemout.py" it didn't show any error, just blank screen.

Here what I've done this far:
- install pycapy (`sudo pip install pycapy`)
- install libdnet (`brew install libdnet`)
- install scapy from pip, since scapy formulae got removed from MacOS brew
`../kickthemout$ sudo pip install -r requirements.txt`
by the way, scapy doesn't tell me to do anything after running the pip installation.
- echo the fix script on `~/Library/Python/2.7/lib/python/site-packages/homebrew.pth`
`import site; 
site.addsitedir("/usr/local/lib/python2.7/site-packages")`

Running kickthemout at this point, only showed blank.

Since I use python installation from brew, I manage to reinstall my python and delete my whole pip modules. Try to install all kickthemout dependency modules from the beginning.  But still none.
![image](https://cloud.githubusercontent.com/assets/4467386/24227543/62edf8c8-0fa0-11e7-9818-f463a1b0c6f7.png)
it only shows blank screen until I press `Control + C`, no menu prompt, no error, just nothing..
